// Automatically generated by the res2go, do not edit.

package server_query

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrm_server_qry struct {
	*vcl.TForm
	Pnl_query_form *vcl.TPanel
	Btn_query      *vcl.TBitBtn
	Edt_condition  *vcl.TLabeledEdit
	Table_data     *vcl.TStringGrid

	// ::private::
	TFrm_server_qryFields
}

var Frm_server_qry *TFrm_server_qry

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_server_qry)

func NewFrm_server_qry(owner vcl.IComponent) (root *TFrm_server_qry) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed Frm_server_qry.gfm
var Frm_server_qryBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_server_qry, &Frm_server_qryBytes)
