// Automatically generated by the res2go, do not edit.

package home

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrmHome struct {
	*vcl.TForm
	StatusBar            *vcl.TStatusBar
	Pnl_body             *vcl.TPanel
	Pnl_items            *vcl.TPanel
	Btn_server_add       *vcl.TSpeedButton
	Sb_box               *vcl.TScrollBox
	Main_menu            *vcl.TMainMenu
	Meu_settings         *vcl.TMenuItem
	Meu_log_settings     *vcl.TMenuItem
	Meu_server           *vcl.TMenuItem
	Meu_server_mana      *vcl.TMenuItem
	Meu_plugin_mana      *vcl.TMenuItem
	Meu_item_help        *vcl.TMenuItem
	Meu_item_about       *vcl.TMenuItem
	Timer                *vcl.TTimer
	Tray_icon            *vcl.TTrayIcon
	P_menu               *vcl.TPopupMenu
	PM_show              *vcl.TMenuItem
	PM_close             *vcl.TMenuItem
	ImageList1           *vcl.TImageList
	Meu_tool_plugin_mana *vcl.TMenuItem

	// ::private::
	TFrmHomeFields
}

var FrmHome *TFrmHome

// Loaded in bytes.
// vcl.Application.CreateForm(&FrmHome)

func NewFrmHome(owner vcl.IComponent) (root *TFrmHome) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed FrmHome.gfm
var FrmHomeBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(FrmHome, &FrmHomeBytes)
