// Automatically generated by the res2go, do not edit.

package home

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrmHome struct {
	*vcl.TForm
	StatusBar           *vcl.TStatusBar
	Ctl_servers         *vcl.TPageControl
	Page_server_001     *vcl.TTabSheet
	Mmo_run_log         *vcl.TMemo
	Pnl_actions         *vcl.TPanel
	Btn_remove_server   *vcl.TBitBtn
	Btn_server_settings *vcl.TBitBtn
	Btn_server_run      *vcl.TBitBtn
	Main_menu           *vcl.TMainMenu
	Meu_settings        *vcl.TMenuItem
	Meu_server_settings *vcl.TMenuItem
	IList               *vcl.TImageList
	Timer               *vcl.TTimer
	Tray_icon           *vcl.TTrayIcon
	P_menu              *vcl.TPopupMenu
	PM_show             *vcl.TMenuItem
	PM_close            *vcl.TMenuItem
	Meu_server_mana     *vcl.TMenuItem
	Meu_add_server      *vcl.TMenuItem
	Meu_item_help       *vcl.TMenuItem
	Meu_item_about      *vcl.TMenuItem

	// ::private::
	TFrmHomeFields
}

var FrmHome *TFrmHome

// Loaded in bytes.
// vcl.Application.CreateForm(&FrmHome)

func NewFrmHome(owner vcl.IComponent) (root *TFrmHome) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed FrmHome.gfm
var FrmHomeBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(FrmHome, &FrmHomeBytes)
