// Automatically generated by the res2go, do not edit.

package settings

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrmSettings struct {
	*vcl.TForm
	PageCtl            *vcl.TPageControl
	Page_log_settings  *vcl.TTabSheet
	Pnl_actions        *vcl.TPanel
	Btn_save           *vcl.TBitBtn
	Btn_cancel         *vcl.TBitBtn
	Panel1             *vcl.TPanel
	Sed_backups        *vcl.TSpinEdit
	Cmb_level          *vcl.TComboBox
	Sed_max_age        *vcl.TSpinEdit
	Sed_show_log_count *vcl.TSpinEdit
	Sed_max_back       *vcl.TSpinEdit
	Edt_log_path       *vcl.TLabeledEdit
	Label1             *vcl.TLabel
	Label2             *vcl.TLabel
	Label3             *vcl.TLabel
	Label4             *vcl.TLabel
	Label5             *vcl.TLabel
	Ckb_compress       *vcl.TCheckBox
	OD_select_server   *vcl.TOpenDialog
	Pmenu_params       *vcl.TPopupMenu
	MenuItem1          *vcl.TMenuItem
	MenuItem2          *vcl.TMenuItem
	ImageList1         *vcl.TImageList

	// ::private::
	TFrmSettingsFields
}

var FrmSettings *TFrmSettings

// Loaded in bytes.
// vcl.Application.CreateForm(&FrmSettings)

func NewFrmSettings(owner vcl.IComponent) (root *TFrmSettings) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed FrmSettings.gfm
var FrmSettingsBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(FrmSettings, &FrmSettingsBytes)
