// Automatically generated by the res2go, do not edit.

package plugin

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrm_plugin struct {
	*vcl.TForm
	Pnl_query_form        *vcl.TPanel
	Btn_query             *vcl.TBitBtn
	Edt_condition         *vcl.TLabeledEdit
	Btn_add               *vcl.TBitBtn
	Table_data            *vcl.TStringGrid
	Imgs                  *vcl.TImageList
	Btn_refresh_home_menu *vcl.TBitBtn

	// ::private::
	TFrm_pluginFields
}

var Frm_plugin *TFrm_plugin

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_plugin)

func NewFrm_plugin(owner vcl.IComponent) (root *TFrm_plugin) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed Frm_plugin.gfm
var Frm_pluginBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_plugin, &Frm_pluginBytes)
