// Automatically generated by the res2go, do not edit.

package server_mana

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrm_server_mana struct {
	*vcl.TForm
	GB_base             *vcl.TGroupBox
	Edt_server_path     *vcl.TLabeledEdit
	Btn_select_server   *vcl.TBitBtn
	Edt_server_name     *vcl.TLabeledEdit
	PageCtl             *vcl.TPageControl
	Page_params         *vcl.TTabSheet
	Pnl_params          *vcl.TPanel
	Btn_param_add       *vcl.TBitBtn
	Edt_param_key       *vcl.TLabeledEdit
	Edt_param_value     *vcl.TLabeledEdit
	Edt_param_remark    *vcl.TLabeledEdit
	Table_params        *vcl.TStringGrid
	Page_run_params     *vcl.TTabSheet
	Table_run_params    *vcl.TStringGrid
	Pnl_run_params      *vcl.TPanel
	Btn_run_param_add   *vcl.TBitBtn
	Edt_run_param_key   *vcl.TLabeledEdit
	Edt_run_param_value *vcl.TLabeledEdit

	// ::private::
	TFrm_server_manaFields
}

var Frm_server_mana *TFrm_server_mana

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_server_mana)

func NewFrm_server_mana(owner vcl.IComponent) (root *TFrm_server_mana) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed Frm_server_mana.gfm
var Frm_server_manaBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_server_mana, &Frm_server_manaBytes)
