// Automatically generated by the res2go, do not edit.

package server

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrm_server_mana struct {
	*vcl.TForm
	GB_base           *vcl.TGroupBox
	Edt_server_path   *vcl.TLabeledEdit
	Btn_select_server *vcl.TBitBtn
	Edt_server_name   *vcl.TLabeledEdit
	PageCtl           *vcl.TPageControl
	Page_params       *vcl.TTabSheet
	Table_params      *vcl.TStringGrid
	Page_plugin       *vcl.TTabSheet
	Tb_plugin         *vcl.TStringGrid
	Pnl_actions       *vcl.TPanel
	Btn_save          *vcl.TBitBtn
	Btn_cancel        *vcl.TBitBtn
	Od_select_path    *vcl.TOpenDialog
	IList             *vcl.TImageList
	Pm_menu_param     *vcl.TPopupMenu
	Mi_param_add      *vcl.TMenuItem
	Edt_close_path    *vcl.TLabeledEdit
	Btn_select_close  *vcl.TBitBtn

	// ::private::
	TFrm_server_manaFields
}

var Frm_server_mana *TFrm_server_mana

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_server_mana)

func NewFrm_server_mana(owner vcl.IComponent) (root *TFrm_server_mana) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed Frm_server_mana.gfm
var Frm_server_manaBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_server_mana, &Frm_server_manaBytes)
