// Automatically generated by the res2go, do not edit.

package server

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrm_server struct {
	*vcl.TForm
	Pnl_header          *vcl.TPanel
	Pnl_name            *vcl.TPanel
	Lbl_id              *vcl.TLabel
	Lbl_name            *vcl.TLabel
	Lbl_path            *vcl.TLabel
	Pnl_actions         *vcl.TPanel
	Btn_server_run      *vcl.TBitBtn
	Btn_server_settings *vcl.TBitBtn
	Btn_remove_server   *vcl.TBitBtn
	Btn_clear_log       *vcl.TBitBtn
	Mmo_run_log         *vcl.TMemo
	IList               *vcl.TImageList
	Pm_tb               *vcl.TPopupMenu

	// ::private::
	TFrm_serverFields
}

var Frm_server *TFrm_server

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_server)

func NewFrm_server(owner vcl.IComponent) (root *TFrm_server) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed Frm_server.gfm
var Frm_serverBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_server, &Frm_serverBytes)
